2022-07-25 21:14:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-25 22:23:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-25 22:53:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-25 22:53:49 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-25 22:53:49 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-25 23:02:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-25 23:04:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-25 23:39:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-25 23:39:19 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-25 23:39:19 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-26 01:16:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 01:56:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 01:56:20 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 01:56:20 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-26 02:06:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 02:43:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-26 05:50:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 07:08:16 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 07:12:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-26 07:12:21 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 07:12:21 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-26 07:12:51 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 07:12:51 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 07:12:51 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-26 07:41:55 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 07:45:51 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 07:45:51 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 07:45:51 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-26 08:42:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 08:43:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 09:15:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 09:43:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 10:29:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 11:17:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 12:27:52 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 12:27:52 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 12:27:52 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-26 13:45:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 14:02:52 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 14:02:52 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 14:02:52 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-26 14:02:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-26 14:02:53 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 14:02:53 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-26 14:17:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-26 14:17:53 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 14:17:53 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-26 14:18:23 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-26 14:18:23 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 14:18:23 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-26 14:34:23 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 15:30:09 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-07-26 15:34:28 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 16:04:52 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 16:04:52 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 16:04:52 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-26 16:34:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 16:56:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 17:09:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-26 17:09:53 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 17:09:53 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-26 17:11:33 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 17:37:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-26 17:37:53 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 17:37:53 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-26 17:46:13 WARNING (MainThread) [homeassistant.components.automation.2f_keting_switch_on_single_press_2] 2f keting switch on single press: Already running
2022-07-26 17:50:23 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 17:50:23 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 17:50:23 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-26 18:00:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-26 18:00:53 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-26 18:00:53 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-26 18:02:38 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 18:26:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 18:59:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-26 20:15:01 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-26 20:25:03 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 20:26:08 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_ke_ting_deng or it is/they are currently not available
2022-07-26 20:26:10 WARNING (MainThread) [homeassistant.components.automation.2f_keting_switch_on_double_press] 2f keting switch on double press: Already running
2022-07-26 20:37:32 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 21:16:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 21:32:59 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 21:39:23 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 21:45:29 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-26 22:25:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 22:37:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-26 23:20:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-27 00:16:24 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 00:16:24 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 00:16:24 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 00:53:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 01:10:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 01:45:28 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 03:40:22 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-27 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-27 04:09:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 04:52:25 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 04:52:25 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 04:52:25 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 05:41:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 05:56:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 05:58:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 07:31:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 07:31:26 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 07:31:26 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 07:37:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 07:37:56 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 07:37:56 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-27 07:42:33 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 07:51:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 08:04:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 08:04:26 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 08:04:26 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 08:27:25 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 08:27:25 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 08:27:25 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 09:44:55 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 09:44:55 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 09:44:55 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-27 09:56:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 09:56:56 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 09:56:56 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:06:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 10:06:56 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:06:56 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:11:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 10:11:26 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:11:26 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:11:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 10:11:26 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:11:26 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:27:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 10:27:56 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:27:56 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:38:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 10:38:26 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:38:26 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:42:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 10:42:26 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:42:26 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:46:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 10:46:56 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:46:56 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 10:47:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 10:47:56 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 10:47:56 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:01:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 11:08:30 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 11:11:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 11:11:26 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:11:26 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:20:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 11:20:26 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:20:26 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:22:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 11:22:57 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:22:57 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:23:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 11:23:26 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:23:26 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:32:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 11:32:56 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:32:56 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:36:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 11:36:26 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:36:26 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:49:49 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 11:49:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 11:49:57 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:49:57 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:56:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 11:56:56 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:56:56 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:58:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 11:58:26 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:58:26 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:58:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 11:58:27 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 11:58:27 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 11:59:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 12:05:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 12:05:56 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 12:05:56 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 12:13:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 12:13:56 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 12:13:56 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 12:23:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 12:32:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 12:32:26 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 12:32:26 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 12:32:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 12:32:27 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 12:32:27 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 12:47:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 12:47:57 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 12:47:57 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 12:56:06 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 13:01:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 13:01:57 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:01:57 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:02:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 13:02:26 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:02:26 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:02:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 13:02:27 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:02:27 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:08:53 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 13:18:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 13:18:26 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:18:26 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:18:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 13:18:27 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:18:27 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:18:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 13:18:57 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:18:57 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:27:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 13:27:26 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:27:26 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:41:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 13:41:26 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:41:26 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 13:53:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 13:53:57 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 13:53:57 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 14:21:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 14:25:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 14:25:57 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 14:25:57 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 16:08:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 16:08:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 16:08:57 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 16:08:57 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 16:32:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 16:32:27 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 16:32:27 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 16:32:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 16:32:27 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 16:32:27 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-27 16:41:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 16:41:57 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 16:41:57 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 16:50:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 16:54:38 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 16:55:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 16:55:57 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 16:55:57 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 17:12:23 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 17:32:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 17:35:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 17:35:58 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 17:35:58 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-27 17:41:37 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 17:54:14 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 18:08:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 18:08:28 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 18:08:28 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 18:09:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 18:09:28 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 18:09:28 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 18:10:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 18:10:58 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 18:10:58 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-27 18:11:51 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-27 18:11:51 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-27 18:35:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 18:38:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 18:38:27 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 18:38:27 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 19:12:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 19:12:27 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 19:12:27 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-27 19:14:28 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 19:24:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 19:24:57 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 19:24:57 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-27 19:28:11 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 19:42:14 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 19:50:57 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 19:50:57 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 19:50:57 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 20:14:11 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-27 20:20:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 20:20:27 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 20:20:27 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-27 20:20:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 20:20:28 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 20:20:28 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-27 20:24:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 20:40:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-27 20:40:28 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 20:40:28 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-27 20:41:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 20:41:28 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 20:41:28 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 20:47:33 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 20:47:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 20:47:58 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 20:47:58 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-27 21:17:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 21:17:58 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 21:17:58 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-27 21:26:39 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 21:39:09 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-27 21:44:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 21:44:28 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 21:44:28 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 21:44:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 21:44:58 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 21:44:58 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 22:03:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 22:09:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 22:09:28 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 22:09:28 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-27 22:20:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-27 22:20:28 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 22:20:28 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-27 22:32:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 22:32:58 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 22:32:58 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-27 23:19:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-27 23:19:28 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-27 23:19:28 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-27 23:30:38 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-27 23:32:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 00:11:50 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 00:59:29 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-28 00:59:29 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 00:59:29 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-28 01:18:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 01:18:58 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 01:18:58 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-28 03:33:59 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 03:33:59 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 03:33:59 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-28 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-28 04:09:29 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 04:09:29 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 04:09:29 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-28 04:48:55 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 05:11:00 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 05:47:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 07:10:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 07:21:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 07:30:06 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 07:34:52 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-28 08:05:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 08:12:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 08:41:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-28 10:22:01 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-28 10:22:01 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 10:22:01 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-28 11:13:11 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 12:24:58 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 13:01:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-28 13:34:16 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 14:04:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 14:46:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 14:48:49 WARNING (MainThread) [homeassistant.components.automation.1f_woshi_switch_on_single_press] 单击一楼卧室灯: Already running
2022-07-28 15:41:21 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 16:05:03 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 16:39:01 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 16:39:01 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 16:39:01 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-28 16:55:23 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 16:59:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 17:37:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 17:37:31 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 17:37:31 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-28 18:30:32 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-28 18:30:32 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 18:30:32 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-28 18:55:32 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-28 18:55:32 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 18:55:32 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-28 19:33:13 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 20:13:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-28 20:26:28 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 20:48:33 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-28 22:06:39 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-28 22:19:09 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-28 22:40:02 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-28 22:40:02 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-28 22:40:02 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-28 23:47:38 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 00:21:03 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-29 00:21:03 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 00:21:03 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-29 02:50:43 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 03:17:48 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 03:45:53 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-29 05:19:34 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-29 05:19:34 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 05:19:34 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-29 05:39:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-29 05:39:04 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 05:39:04 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-29 05:59:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-29 05:59:04 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 05:59:04 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-29 06:16:34 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-29 06:16:34 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 06:16:34 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-29 06:17:18 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 06:27:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-29 06:27:04 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 06:27:04 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-29 07:23:19 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-29 07:43:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-29 07:43:04 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 07:43:04 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-29 08:40:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-29 08:40:35 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 08:40:35 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-29 08:54:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 08:55:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-29 08:55:35 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 08:55:35 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-29 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-29 09:11:26 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 10:33:05 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-29 10:33:05 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 10:33:05 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-29 11:20:23 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 12:11:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 12:14:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-29 12:14:35 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 12:14:35 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-29 13:16:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-29 13:51:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 14:03:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-29 14:03:36 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 14:03:36 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-29 14:33:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-29 14:33:36 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 14:33:36 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-29 15:22:31 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 15:27:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-29 15:27:36 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 15:27:36 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-29 15:28:35 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-29 15:28:36 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-29 15:28:36 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-29 16:40:36 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 18:22:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 18:44:41 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 19:09:46 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 19:49:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 20:11:51 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 20:12:26 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-29 21:22:20 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-29 21:23:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 21:26:12 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-29 21:40:12 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-29 21:45:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 22:24:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-29 22:58:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-29 23:52:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 01:04:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-30 01:04:07 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 01:04:07 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-30 02:34:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-30 02:34:38 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 02:34:38 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-30 02:35:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 02:35:38 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 02:35:38 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-30 02:36:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 02:36:08 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 02:36:08 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-30 02:52:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 02:52:38 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 02:52:38 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-30 02:54:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 02:54:38 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 02:54:38 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-30 03:45:57 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-30 04:24:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 04:36:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 05:30:08 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 05:30:08 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 05:30:08 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-30 05:30:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 05:30:38 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 05:30:38 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-30 05:30:38 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-30 05:30:38 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 05:30:38 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-30 07:10:05 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 09:07:02 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 10:18:45 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 11:11:39 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-30 11:11:39 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 11:11:39 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-30 12:15:50 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 12:50:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 13:01:07 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 13:17:29 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 14:00:16 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 14:04:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-30 14:04:40 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 14:04:40 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-30 14:17:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-30 14:17:40 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 14:17:40 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-30 14:36:12 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 15:08:49 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 16:05:40 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-30 16:05:40 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 16:05:40 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-30 16:46:55 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 17:58:00 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 18:25:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 18:25:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 19:01:43 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 19:16:01 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 19:31:16 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 19:34:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 19:34:11 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 19:34:11 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-30 19:36:05 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 19:42:06 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_ke_ting_deng or it is/they are currently not available
2022-07-30 19:53:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 20:11:31 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-30 20:36:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-30 20:57:17 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 21:13:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 21:13:11 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 21:13:11 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-30 21:19:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 21:25:11 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-30 21:25:11 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 21:25:11 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-30 21:41:14 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 21:53:46 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-30 23:42:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-30 23:51:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-30 23:51:12 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-30 23:51:12 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-31 01:06:22 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 02:17:27 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 02:48:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-07-31 03:51:32 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-31 04:05:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 04:08:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 冰柜 (SP mini 3 at 192.168.1.17) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 04:09:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 04:09:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 04:09:12 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 04:09:12 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 04:09:12 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-31 04:09:12 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 04:09:12 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-31 04:09:42 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 04:09:42 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 04:09:42 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-31 05:32:26 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-07-31 06:02:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 07:04:29 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 07:06:11 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 08:01:37 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 08:05:13 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 08:05:13 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 08:05:13 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-31 08:20:42 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 09:25:47 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 09:34:43 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 09:34:43 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 09:34:43 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-31 09:49:16 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 10:44:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 10:44:14 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 10:44:14 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-31 10:53:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 10:53:14 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 10:53:14 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-31 11:14:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 11:14:14 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 11:14:14 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-31 11:28:21 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 12:00:26 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 12:50:52 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 14:06:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 14:45:14 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 14:45:14 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 14:45:14 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-07-31 15:06:57 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 16:45:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 16:45:15 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 16:45:15 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:40:46 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 智能遥控RMPRO (RM pro at 192.168.1.19) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 17:41:02 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 17:41:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 冰柜 (SP mini 3 at 192.168.1.17) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 17:41:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 17:41:15 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:41:15 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:41:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 17:41:15 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:41:15 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:41:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 17:41:25 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:41:25 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 17:41:25 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:41:31 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 17:41:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 17:41:45 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:41:45 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:41:45 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 17:41:45 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:41:45 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:43:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 17:43:15 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:43:15 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:43:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 17:43:15 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:43:15 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:43:25 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 17:43:25 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:43:25 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-07-31 17:52:20 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 17:53:15 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-07-31 17:53:15 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 17:53:15 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-07-31 18:08:56 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 18:59:55 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 19:33:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 20:10:34 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-07-31 20:29:08 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 20:41:51 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 智能遥控RMPRO (RM pro at 192.168.1.19) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 20:42:16 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 21:32:37 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 21:45:07 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-07-31 21:50:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 21:50:46 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 21:50:46 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-07-31 22:02:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 22:02:16 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 22:02:16 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-07-31 22:10:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 22:10:46 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 22:10:46 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-07-31 22:31:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 22:45:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-07-31 23:10:16 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-07-31 23:10:16 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 23:10:16 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-07-31 23:58:46 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-07-31 23:58:46 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-07-31 23:58:46 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 03:17:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 03:48:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 03:48:17 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 03:48:17 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-01 04:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced devices cdfee5b5c3de20f51b5c596e260e8af2 or it is/they are currently not available
2022-08-01 04:12:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 04:12:17 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 04:12:17 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 04:12:17 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 04:12:17 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-01 04:12:17 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-08-01 04:12:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 04:12:47 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 04:12:47 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-01 04:27:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-01 05:38:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 06:01:02 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-08-01 06:06:47 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 06:06:47 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 06:06:47 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-01 07:10:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 07:25:36 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 07:55:42 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-01 08:53:41 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-01 09:40:18 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 09:40:18 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 09:40:18 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-01 09:41:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 11:07:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-01 13:36:46 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 13:42:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 14:23:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 14:23:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-01 14:23:49 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 14:23:49 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 14:23:49 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-01 14:23:49 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-01 14:42:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 15:20:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 15:20:49 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 15:20:49 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-08-01 15:22:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-01 15:22:49 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 15:22:49 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-01 15:35:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 15:54:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 16:46:19 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-01 16:46:19 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 16:46:19 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-01 16:52:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-01 18:00:49 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 18:00:49 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 18:00:49 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 18:24:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 18:24:20 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 18:24:20 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 18:50:51 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 20:29:18 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-08-01 20:30:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 20:30:50 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 20:30:50 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 20:41:48 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng or it is/they are currently not available
2022-08-01 20:47:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 20:47:50 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 20:47:50 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 20:52:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-01 20:52:20 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 20:52:20 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-01 21:02:07 WARNING (MainThread) [homeassistant.components.automation.1f_woshi_switch_on_single_press] 单击一楼卧室灯: Already running
2022-08-01 21:49:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 21:49:50 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 21:49:50 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-01 21:51:56 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-01 22:17:20 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-01 22:17:20 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 22:17:20 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-01 22:18:50 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-01 22:18:50 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-01 22:18:50 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-01 23:27:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 00:08:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-02 00:18:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 00:39:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 00:52:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 01:34:01 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 03:07:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 04:00:12 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-08-02 04:12:06 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 04:12:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 04:12:21 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-02 04:12:21 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 04:12:21 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-02 04:30:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 07:02:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 07:05:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-02 07:05:22 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 07:05:22 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-02 08:49:11 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-02 09:37:16 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 09:41:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 09:58:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-02 09:58:22 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 09:58:22 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-02 10:18:22 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-02 10:18:22 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 10:18:22 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-02 11:37:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 11:50:53 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-02 11:50:53 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 11:50:53 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-02 11:58:21 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 13:27:23 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-02 13:27:23 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-02 13:27:23 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-02 17:06:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 17:19:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 18:08:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 19:31:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 20:24:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-02 22:43:26 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-03 00:55:25 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-03 00:55:25 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 00:55:25 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-03 01:17:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-03 03:15:56 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-03 03:15:56 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 03:15:56 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-03 04:12:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 04:21:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 04:26:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 05:02:26 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-03 05:02:26 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 05:02:26 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-03 05:24:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 05:55:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-03 10:35:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-03 10:35:27 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 10:35:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-03 10:35:27 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-03 10:35:27 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 10:35:27 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-08-03 10:37:27 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-03 10:37:27 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 10:37:27 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-03 11:44:26 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 11:58:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 12:57:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 13:21:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-03 13:21:58 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 13:21:58 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-03 13:47:31 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 14:29:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 15:02:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 15:14:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 15:16:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-03 15:18:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 15:35:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 15:44:28 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-03 15:44:28 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 15:44:28 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-03 16:02:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 16:24:36 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 17:58:41 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 19:53:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-03 21:12:59 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-03 21:12:59 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 21:12:59 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-03 22:53:29 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-03 22:53:29 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-03 22:53:29 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-04 00:20:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 01:42:46 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 02:18:51 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 03:54:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 04:18:27 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-08-04 04:42:56 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 05:54:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 07:05:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 07:05:25 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 冰柜 (SP mini 3 at 192.168.1.17) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 07:05:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-04 07:05:31 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 07:05:31 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
2022-08-04 07:05:31 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-04 07:05:31 ERROR (SyncWorker_3) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 07:05:31 ERROR (SyncWorker_3) [xiaomi_gateway] No data in response from hub None
2022-08-04 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-04 09:04:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 09:07:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 10:38:01 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 10:44:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 11:55:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 11:59:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 12:25:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 16:06:14 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 16:15:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-04 16:15:33 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 16:15:33 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-04 16:16:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d0001a64708 is taking over 10 seconds
2022-08-04 16:16:33 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 16:16:33 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-04 16:34:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 16:35:33 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-04 16:35:33 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 16:35:33 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-04 18:55:19 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 19:19:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 21:14:24 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 23:26:04 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-04 23:26:04 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-04 23:26:04 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-04 23:31:06 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-04 23:51:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 00:50:11 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 04:30:15 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: Unable to connect to servers to test latency.
2022-08-05 04:31:16 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 06:02:29 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 07:28:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 08:09:34 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 08:16:39 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 08:43:44 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 09:00:00 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.er_lou_wo_shi_deng, switch.yi_lou_wo_shi_deng or it is/they are currently not available
2022-08-05 09:57:21 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 10:04:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-05 10:04:06 ERROR (SyncWorker_6) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 10:04:06 ERROR (SyncWorker_6) [xiaomi_gateway] No data in response from hub None
2022-08-05 10:34:04 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 10:38:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-05 10:38:36 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 10:38:36 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:10:26 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:12:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-05 11:12:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-05 11:12:06 ERROR (SyncWorker_4) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 11:12:06 ERROR (SyncWorker_7) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 11:12:06 ERROR (SyncWorker_4) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:12:06 ERROR (SyncWorker_7) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:12:09 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:12:31 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:12:35 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 冰柜 (SP mini 3 at 192.168.1.17) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:12:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-05 11:12:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-05 11:12:36 ERROR (SyncWorker_8) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 11:12:36 ERROR (SyncWorker_8) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:12:36 ERROR (SyncWorker_1) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 11:12:36 ERROR (SyncWorker_1) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:29:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2022-08-05 11:29:49 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:29:59 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 智能遥控RMPRO (RM pro at 192.168.1.19) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:30:06 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.plug_158d00015d1bf5 is taking over 10 seconds
2022-08-05 11:30:06 ERROR (SyncWorker_0) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 11:30:06 ERROR (SyncWorker_0) [xiaomi_gateway] No data in response from hub None
2022-08-05 11:33:15 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 11:33:54 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 书桌插排 (MP1-1K4S at 192.168.1.15) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 12:15:36 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.door_window_sensor_158d000128fa46 is taking over 10 seconds
2022-08-05 12:15:36 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 12:15:36 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-05 13:23:36 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 1FTV (MP1-1K4S at 192.168.1.16) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 13:45:20 ERROR (MainThread) [homeassistant.components.broadlink.updater] Error fetching 电视插排 (MP1-1K4S at 192.168.1.14) data: [Errno -4000] Network timeout: No response received within 5s
2022-08-05 14:08:07 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.my_nas is taking over 10 seconds
2022-08-05 14:09:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.nas is taking over 10 seconds
2022-08-05 14:09:10 WARNING (MainThread) [homeassistant.helpers.entity] Update of binary_sensor.d191g is taking over 10 seconds
2022-08-05 14:09:10 WARNING (MainThread) [homeassistant.components.switch] Updating wake_on_lan switch took longer than the scheduled update interval 0:00:30
2022-08-05 14:09:10 WARNING (MainThread) [homeassistant.components.switch] Updating xiaomi_aqara switch took longer than the scheduled update interval 0:00:30
2022-08-05 14:09:10 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating xiaomi_aqara binary_sensor took longer than the scheduled update interval 0:00:30
2022-08-05 14:09:48 WARNING (MainThread) [homeassistant.components.switch] Updating wake_on_lan switch took longer than the scheduled update interval 0:00:30
2022-08-05 14:10:18 WARNING (MainThread) [homeassistant.components.switch] Updating wake_on_lan switch took longer than the scheduled update interval 0:00:30
2022-08-05 14:10:58 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.my_nas is taking over 10 seconds
2022-08-05 14:11:34 WARNING (MainThread) [homeassistant.helpers.entity] Update of switch.my_nas is taking over 10 seconds
2022-08-05 14:11:44 ERROR (SyncWorker_2) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 14:11:44 ERROR (SyncWorker_5) [xiaomi_gateway] Cannot connect to Gateway
2022-08-05 14:11:44 ERROR (SyncWorker_5) [xiaomi_gateway] No data in response from hub None
2022-08-05 14:11:44 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
